"""Make background_jobs poster_id nullable

Revision ID: 9f0aeed0e2ad
Revises: 93dda7048394
Create Date: 2025-12-27 01:23:31.193744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0aeed0e2ad'
down_revision: Union[str, None] = '93dda7048394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('background_jobs', 'poster_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('poster_products', sa.Column('artikel_nr', sa.String(length=100), nullable=False))
    op.add_column('poster_products', sa.Column('german_name', sa.String(length=500), nullable=False))
    op.add_column('poster_products', sa.Column('chinese_name', sa.String(length=500), nullable=True))
    op.add_column('poster_products', sa.Column('weight', sa.String(length=100), nullable=True))
    op.add_column('poster_products', sa.Column('product_image_base64', sa.Text(), nullable=True))
    op.alter_column('poster_products', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_poster_products_artikel_nr'), 'poster_products', ['artikel_nr'], unique=False)
    op.drop_constraint('poster_products_product_id_fkey', 'poster_products', type_='foreignkey')
    op.drop_column('poster_products', 'display_name')
    op.drop_column('poster_products', 'display_weight')
    op.alter_column('posters', 'background_image_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('posters', 'theme_text')
    op.drop_column('posters', 'llm_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posters', sa.Column('llm_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posters', sa.Column('theme_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('posters', 'background_image_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('poster_products', sa.Column('display_weight', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('poster_products', sa.Column('display_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key('poster_products_product_id_fkey', 'poster_products', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_poster_products_artikel_nr'), table_name='poster_products')
    op.alter_column('poster_products', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('poster_products', 'product_image_base64')
    op.drop_column('poster_products', 'weight')
    op.drop_column('poster_products', 'chinese_name')
    op.drop_column('poster_products', 'german_name')
    op.drop_column('poster_products', 'artikel_nr')
    op.alter_column('background_jobs', 'poster_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
